# Generated by Django 4.2 on 2024-10-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_productuserrating'),
        ('users', '0002_alter_customuser_avatar_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_product',
            field=models.ManyToManyField(to='market.product'),
        ),
    ]
