# Generated by Django 4.2 on 2024-09-04 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111, verbose_name='название')),
                ('price', models.PositiveSmallIntegerField(verbose_name='цена')),
                ('sales_percent', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='скидки')),
                ('description', models.TextField(verbose_name='описмание')),
                ('preview_image', models.ImageField(upload_to='')),
                ('is_new', models.BooleanField()),
                ('new_expiry_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='продукты', to='market.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='market.product')),
            ],
        ),
    ]
