# Generated by Django 4.2 on 2024-09-12 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_delete_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_descriptions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_percent',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='скидки'),
        ),
    ]
