# Generated by Django 4.2 on 2024-10-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_productuserrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
